name: build_and_test

on: [push]

jobs:
  build-test-linux:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: CodeEvaluation
          environment-file: environment.dev.yaml
          auto-activate-base: false
      - name: Lint with flake8
        run: flake8 .